// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/yh/button/button.vue')['default']
    Calendar: typeof import('./src/components/yh/calendar/calendar.vue')['default']
    Divider: typeof import('./src/components/yh/divider/divider.vue')['default']
    DropdownItem: typeof import('./src/components/yh/dropdown-item/dropdown-item.vue')['default']
    DropdownMenu: typeof import('./src/components/yh/dropdown-menu/dropdown-menu.vue')['default']
    Header: typeof import('./src/components/yh/calendar/header.vue')['default']
    Icon: typeof import('./src/components/yh/icon/icon.vue')['default']
    Info: typeof import('./src/components/yh/info/info.vue')['default']
    Loading: typeof import('./src/components/yh/loading/loading.vue')['default']
    Month: typeof import('./src/components/yh/calendar/month.vue')['default']
    Overlay: typeof import('./src/components/yh/overlay/overlay.vue')['default']
    Popup: typeof import('./src/components/yh/popup/popup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('./src/components/yh/skeleton/skeleton.vue')['default']
    Toast: typeof import('./src/components/yh/toast/toast.vue')['default']
    Transition: typeof import('./src/components/yh/transition/transition.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    YhAvatar: typeof import('./src/components/common/yh-avatar/yh-avatar.vue')['default']
    YhButton: typeof import('./src/components/common/yh-button/yh-button.vue')['default']
    YhCardApply: typeof import('./src/components/project/yh-card-apply/yh-card-apply.vue')['default']
    YhCardApplyProcess: typeof import('./src/components/project/yh-card-apply-process/yh-card-apply-process.vue')['default']
    YhCardEnterprisesReport: typeof import('./src/components/project/yh-card-enterprises-report/yh-card-enterprises-report.vue')['default']
    YhCardEventHeadlines: typeof import('./src/components/project/yh-card-event-headlines/yh-card-event-headlines.vue')['default']
    YhCardMessage: typeof import('./src/components/project/yh-card-message/yh-card-message.vue')['default']
    YhCardPolicy: typeof import('./src/components/project/yh-card-policy/yh-card-policy.vue')['default']
    YhCardPublicity: typeof import('./src/components/project/yh-card-publicity/yh-card-publicity.vue')['default']
    YhCardPublicityComplaint: typeof import('./src/components/project/yh-card-publicity-complaint/yh-card-publicity-complaint.vue')['default']
    YhCardSubsidy: typeof import('./src/components/project/yh-card-subsidy/yh-card-subsidy.vue')['default']
    YhCardWellKnownEnterprises: typeof import('./src/components/project/yh-card-well-known-enterprises/yh-card-well-known-enterprises.vue')['default']
    YhCardWrapper: typeof import('./src/components/common/yh-card-wrapper/yh-card-wrapper.vue')['default']
    YhDeclare: typeof import('./src/components/project/yh-declare/yh-declare.vue')['default']
    YhDeclareAgentInfo: typeof import('./src/components/project/yh-declare-agent-info/yh-declare-agent-info.vue')['default']
    YhDeclareBaseInfo: typeof import('./src/components/project/yh-declare-base-info/yh-declare-base-info.vue')['default']
    YhDeclarePersonnel: typeof import('./src/components/project/yh-declare-personnel/yh-declare-personnel.vue')['default']
    YhDeclarePicker: typeof import('./src/components/project/yh-declare-picker/yh-declare-picker.vue')['default']
    YhDeclarePickerDate: typeof import('./src/components/project/yh-declare-picker-date/yh-declare-picker-date.vue')['default']
    YhDeclareStep: typeof import('./src/components/project/yh-declare-step/yh-declare-step.vue')['default']
    YhImg: typeof import('./src/components/project/yh-img/yh-img.vue')['default']
    YhLoadMore: typeof import('./src/components/common/yh-load-more/yh-load-more.vue')['default']
    YhNoData: typeof import('./src/components/common/yh-no-data/yh-no-data.vue')['default']
    YhNotFound: typeof import('./src/components/common/yh-not-found/yh-not-found.vue')['default']
    YhPanel: typeof import('./src/components/project/yh-panel/yh-panel.vue')['default']
    YhTitle: typeof import('./src/components/project/yh-title/yh-title.vue')['default']
    YhUnderDev: typeof import('./src/components/common/yh-under-dev/yh-under-dev.vue')['default']
    YhWeather: typeof import('./src/components/common/yh-weather/yh-weather.vue')['default']
  }
}
