export { getAgeByIDCard } from './getAgeByIDCard'
export { getBirthdayByIDCard } from './getBirthdayByIDCard'
export { getCurrentDate } from './getCurrentDate'
export { getEnvData } from './getEnvData'
export { getGenderByIDCard } from './getGenderByIDCard'
export { getIsDev } from './getIsDev'
