// export { useCheckAppUpdate } from './useCheckAppUpdate'
export { useCheckIDCard } from './useCheckIDCard'
export { useCheckPhoneNumber } from './useCheckPhoneNumber'
export { useFormatBankCardNumber } from './useFormatBankCardNumber'
export { useFormatIDCardNumber } from './useFormatIDCardNumber'
export { useFormatPhoneNumber } from './useFormatPhoneNumber'
export { useFormatUserName } from './useFormatUserName'
export { useGetAgeByIDCard } from './useGetAgeByIDCard'
export { useGetBirthdayByIDCard } from './useGetBirthdayByIDCard'
export { useGetCurrentDate } from './useGetCurrentDate'
export { useGetGenderByIDCard } from './useGetGenderByIDCard'
export { useGetIsDev } from './useGetIsDev'
