/*
    命名格式说明：
        变量名为全部字母大写，采用“_”符号间隔，前缀加上“M_UPDATE”，方便知道该值是用于更新state中的值
        值与变量名一样
*/
const M_UPDATE_TOKEN = 'M_UPDATE_TOKEN' // 更新token
const M_UPDATE_USER_INFO = 'M_UPDATE_USER_INFO' // 更新用户信息
const M_UPDATE_USER_LIST = 'M_UPDATE_USER_LIST' // 更新用户信息
const M_UPDATE_CORPORATE_INFO = 'M_UPDATE_CORPORATE_INFO' // 更新企业信息
const M_UPDATE_SUBSIDY_PROJECT_DECLARE_INFO =
  'M_UPDATE_SUBSIDY_PROJECT_DECLARE_INFO' // 更新申报信息

export {
  M_UPDATE_USER_INFO,
  M_UPDATE_USER_LIST,
  M_UPDATE_CORPORATE_INFO,
  M_UPDATE_TOKEN,
  M_UPDATE_SUBSIDY_PROJECT_DECLARE_INFO,
}
